### ISSUE TITLE
Item Frame replacement in Charset 

### ISSUE THREAD

**Issue by asiekierka** [bafomdad/realfilingcabinet#17]
An user asked me to notify you, so here goes:

Ever since Charset pipes were created back in late 2015, I wanted to make it so that item frames are used on Shifters (and, later, Observers) to filter their logic in relation to Charset pipes; however, performance concerns stopped me from doing it - entities aren't exactly the cheapest thing in the game, both in terms of tick time and rendering performance.

In Minecraft 1.11.2's version of Charset and later, I plan to replace Item Frames with non-ticking tile entities (using MCMultiPart to allow multiple frames and other tiles in the same block space) for that very reason. However, said user raised the problem of RFC relying on EntityItemFrame (instead of a capability put on tile entities, which is how I'd provide it) to perform filtering, which I was not previously aware of.

Are there ways in which we could work together to make my solution compatible with yours?

**Comment by bafomdad** [comment]
Hi there

Sure, I could work with that. I am mostly interested in seeing how this gets implemented in charset, so that then I could write compatibility for item frames being non-ticking TEs, whenever charset is installed alongside it. Pretty interesting solution to making item frames be not really entities :]
