### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MineplayerHDYT** [bafomdad/realfilingcabinet#29]
Game Crashed after puting an Empty Folder and an Apple in the crafting bench

**Comment by bafomdad** [comment]
Could not reproduce this issue..do you have a crashlog of it happening, and the version you had installed?

**Comment by MineplayerHDYT** [comment]
Mod Version 1.12.1-0.1.21 
Minecraft Version 1.12.2
[crash-2017-12-15_11.25.27-client.txt](https://github.com/bafomdad/realfilingcabinet/files/1562362/crash-2017-12-15_11.25.27-client.txt)

**Comment by MineplayerHDYT** [comment]
i've removed NoMoreRecipeConflict now its not crashing but now i cannot "Craft" it
![2017-12-15_11 46 05](https://user-images.githubusercontent.com/30002045/34038758-bc273d18-e18d-11e7-86a1-e976ebcfd35f.png)

**Comment by bafomdad** [comment]
after some testing, it appears that the culprit is the Compressions mod. looking at the method involved in the stacktrace: https://github.com/Sediments/Compressions/blob/1.12/src/compressions/Base.java#L1622

it appears to return null several times in the method. It should not do that. In minecraft versions 1.11 and onwards, itemstacks are never null. They should return ItemStack.EMPTY whenever they want to give nothing to the player. It is through this weird interaction between Compressions and NoMoreRecipes that the crash happens. Without NoMoreRecipes installed, Compressions will just somehow not crash as it makes some recipes not work, as demonstrated here.

removing Compressions will solve the crashing and the recipes not working

**Comment by MineplayerHDYT** [comment]
thank you but could you fix this that i can use this mod with realfillingcabinet? :D

**Comment by bafomdad** [comment]
I would prefer to not do any temporary solutions when it involves another mod.

the best thing to do here is to take that crash report log up there and report it to the Compressions mod author. If it still continues to be an issue after fixes are made, this issue can be reopened.
