### ISSUE TITLE
Problems using the NBT folder

### ISSUE THREAD

**Issue by jinks** [bafomdad/realfilingcabinet#36]
* RFC version: 1.12.1-0.1.55
* Forge version: 2709

I'm having problems using the NBT folders. I'm not sure if I'm doing something wrong or if it's just not working.

I crafted an NBT folder with a `Death Info` from the Gravestone Mod. The items are all identical except for the NBT data. I put it in an otherwise empty cabinet and then tried to add more items via right-click, but it won't accept any additional notes.

I tried the same with an enchanted book I got from my auto-fisher, with the same result. (Could not add several other books with different enchants.)

Does the NBT structure for each item have to be identical? I.e. same keys, different values?

**Comment by bafomdad** [comment]
I'm not sure how the Death Info from the Gravestone mod works, but assuming that creating a new Death Info would assign NBT values that would be different. And some of those NBT values wouldn't be displayed in some way.

What the NBT folders do is compare the exact NBT value of items, so that they are able to store potions, enchanted books and the like, but only if they are the same potion type/length/amplifier and so on.

**Comment by jinks** [comment]
Alright, that's pretty much the opposite of what I expected it to do.

I was assuming it worked like the old ExU1 filing cabinet where it store the same item with differing NBT.

**Comment by bafomdad** [comment]
Ohh yeah, I can see some confusion there

This mod's strength lies in storing items in large quantities, but due to its design of only storing up to 8 folders per cabinet, it's biggest drawback is not letting one store many _different_ items. It really shines in storing all the cobblestone that'd clutter up the more traditional vanilla chests

**Comment by jinks** [comment]
Alright, that clears up my confusion.
