### ISSUE TITLE
Crash with hover on Filing Cabinet block with folder in it

### ISSUE THREAD

**Issue by generolas121** [bafomdad/realfilingcabinet#43]
**Current Behavior**
Game crashes once the filing block containing empty phial folder is hovered over with a mouse.

**Steps to Reproduce**
1. Place filing cabinet
2. Open it
3. Insert empty phial folder
4. Proceed to crash
5. Reload
6. Get back in game
7. Hover over the filing cabinet again
8. Proceed to crash, again.

**Log** 
https://gist.github.com/generolas121/9104bb1e82332102702e6cf9f53d9bf3

**Comment by bafomdad** [comment]
well, that's not supposed to happen..

the crash happens because the empty phialing folder returns null if it doesn't have any aspect stored in it. I've inserted a condition in the phialing cabinet to prevent one from putting in any empty phialing folders, and to only accept those that actually do have an aspect stored.

note: this crash seems to only happen when you're looking at one with goggles of revealing or anything that shows aspects in containers.
