### ISSUE TITLE
Folders no longer showing contents.

### ISSUE THREAD

**Issue by Bluberry-Kat** [bafomdad/realfilingcabinet#44]
Neither regular file folders nor fluid folders are showing their contents, for whatever reason.
Using v73.
![image](https://user-images.githubusercontent.com/20749209/47260688-4271d100-d48e-11e8-87d8-993a5c9d0ea4.png)
![image](https://user-images.githubusercontent.com/20749209/47260689-47368500-d48e-11e8-95b9-76ce4ca9a16a.png)

**Comment by bafomdad** [comment]
hello, I am wondering if you did an update to the mod from a much older version?

because prior to mod version 1.12.1-0.1.65, the way the folders stored items/fluids/etc within them was done very differently. And there is a function set in place to automatically convert the old way system over to the new one. but anyway, that is just my first question

**Comment by Bluberry-Kat** [comment]
This server has only had v73, and it has had it since the server first started running.

**Comment by bafomdad** [comment]
Okay, so this is an issue I have been unable to reproduce on my own. This is on a server, right? Do you have the modlist present for it, and are there any mods recently added to it?

**Comment by Bluberry-Kat** [comment]
[Here is the modlist.](https://gist.github.com/Birgliss/8c492591a599bee584bc13a3e9c6aaeb)

It is worth mentioning that the issue persisted before I updated the pack past v1, however I will check if it persists in singleplayer, and with the mod by itself.

**Comment by Bluberry-Kat** [comment]
![image](https://user-images.githubusercontent.com/20749209/47278340-2fe2bf00-d596-11e8-8a9f-2020ac295956.png)
Issue.. doesn't persist in singleplayer. Curious.

**Comment by bafomdad** [comment]
a curious issue..I am unable to reproduce it in singleplayer with that modlist as well. I'll have to find out what could possibly be missing on the server/client end

**Comment by bafomdad** [comment]
okay, so an update: the contents of the folders are not shown in the tooltip in any way on a hosted server. They still function as normal; you can view their contents in a filing cabinet with a magnifying glass, or with WAILA. The problem here may come from syncing capability information from the server to the client VIA the item's tooltip. This was more or less narrowed down by the fact that it happened on a hosted server with just this mod installed.

**Comment by bafomdad** [comment]
Okay, so an update

I've written an IContainerListener class, a new  packet, and generally investigating where and when getNBTShareTag loses the nbt data, without really getting anywhere. I thought the folders (and by extension, the suitcases) were intermittently losing their data at random times somehow. It was discovered then that this pretty much only happens in creative mode in multiplayer, and more specifically, when one opens the creative tabs menu.

I really have no answer for this. Several other mods have had similar problems involving multiplayer creative mode and the losing of data of their capabilities and some NBT. There have been little in the way of an elegant solution to this problem, other than doing a pull request to fix this in forge.

Still, it feels like a cop out to say that this is a problem in vanilla/forge, and that the solution is to not open the creative tabs menu while holding any NBT sensitive items in your inventory, The changes made in the attempt to fix this problem will stay, for now.
