### ISSUE TITLE
Folders with Bee Drones in them turn into Forest Drones in Crafting window

### ISSUE THREAD

**Issue by jadeonking** [bafomdad/realfilingcabinet#49]
If you remove a folder from a Filing Cabinet that has (in my case) Wintry, Noble, and Cultivated Drones and attempt to remove them via crafting window it will always be Forest Drones however if you pipe them out via Item Conduits they will be what they are supposed to be

Mod Pack ATM3 Remix B 1.0.0
Mod Version 0.1.73
Minecraft Version 1.12.2

EDIT: here is a video showcasing the bug https://youtu.be/WVd6hWlWzxI
upload speed is atrocious sorry for 480p

**Comment by bafomdad** [comment]
The drones apparently use NBT data to store information about themselves, and you are using a folder that isn't specialized for items with extra data; the NBT folder does all that.

The issue here is that the normal folder is letting you store items with NBT data in them, which isn't supposed to happen. I have released a fix pertaining to this, but please do store your drones in the N-Bee-T folder.

**Comment by jadeonking** [comment]
Another bug I found after switching to NBT folders for bee storage is when you manually place bees inside the Filing cabinet it will duplicate the bee by not initially taking the bee from your hand (in my case it accepted a single stack of bees 3 times before finally taking it from my hand)
